// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ConfirmCancel():Promise<boolean>;

export function GetEulaText():Promise<string>;

export function RunSetupSteps():Promise<void>;
