// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ConfirmCancel() {
  return window['go']['main']['App']['ConfirmCancel']();
}

export function GetEulaText() {
  return window['go']['main']['App']['GetEulaText']();
}

export function RunSetupSteps() {
  return window['go']['main']['App']['RunSetupSteps']();
}
